//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bryntum.Scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBooking : Event
    {
        public short RoomType { get; set; }
        public short RoomStatus { get; set; }
        public decimal Price { get; set; }
        public int GuestId { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
